#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

SUPPORT = r"""
/* ---- KernelPatch bridge: generated by patch-bbr3-pjz110-kpm.py ---- */
#include <linux/atomic.h>
#include <linux/errno.h>
#include <linux/string.h>
#include <asm/alternative.h>

/* KernelPatch exports. They are intentionally resolved by the KPM loader,
 * not by the Linux module loader.
 */
extern unsigned long kallsyms_lookup_name(const char *name);
extern int compat_copy_to_user(void __user *to, const void *from, int n);

static void *(*bbr3_real___kmalloc)(size_t, gfp_t);
static void (*bbr3_real_kfree)(const void *);
static u32 (*bbr3_real_get_random_u32)(void);
static u8 (*bbr3_real_get_random_u8)(void);
static int (*bbr3_real_register_cc)(struct tcp_congestion_ops *);
static void (*bbr3_real_unregister_cc)(struct tcp_congestion_ops *);
static void (*bbr3_real_alt_cb_patch_nops)(struct alt_instr *, __le32 *, __le32 *, int);
static volatile unsigned long *bbr3_real_jiffies;
static const char *bbr3_linux_banner;

static atomic_t bbr3_active_sockets = ATOMIC_INIT(0);
static bool bbr3_registered;
static bool bbr3_runtime_ready;

static void *bbr3_kzalloc(size_t size, gfp_t flags)
{
	void *p;

	if (unlikely(!bbr3_real___kmalloc))
		return NULL;
	p = bbr3_real___kmalloc(size, flags);
	if (p)
		memset(p, 0, size);
	return p;
}

static void bbr3_kfree(const void *p)
{
	if (p && bbr3_real_kfree)
		bbr3_real_kfree(p);
}

static u32 bbr3_tcp_jiffies32(void)
{
	return bbr3_real_jiffies ? (u32)READ_ONCE(*bbr3_real_jiffies) : 0;
}

/* Local definitions deliberately satisfy references emitted by the pinned
 * BBRv3/kernel headers. They tail-call runtime-resolved live kernel symbols.
 */
u32 get_random_u32(void)
{
	return bbr3_real_get_random_u32 ? bbr3_real_get_random_u32() : 0;
}

u8 get_random_u8(void)
{
	if (bbr3_real_get_random_u8)
		return bbr3_real_get_random_u8();
	return (u8)get_random_u32();
}

int tcp_register_congestion_control(struct tcp_congestion_ops *ops)
{
	if (!bbr3_real_register_cc)
		return -ENOENT;
	return bbr3_real_register_cc(ops);
}

void tcp_unregister_congestion_control(struct tcp_congestion_ops *ops)
{
	if (bbr3_real_unregister_cc)
		bbr3_real_unregister_cc(ops);
}

void alt_cb_patch_nops(struct alt_instr *alt, __le32 *origptr,
		       __le32 *updptr, int nr_inst)
{
	if (bbr3_real_alt_cb_patch_nops)
		bbr3_real_alt_cb_patch_nops(alt, origptr, updptr, nr_inst);
}

static inline void bbr3_o13_plb_update_state(const struct sock *sk,
					     struct tcp_plb_state *plb,
					     const int cong_ratio)
{
	(void)sk;
	(void)plb;
	(void)cong_ratio;
}

static inline void bbr3_o13_plb_check_rehash(struct sock *sk,
					     struct tcp_plb_state *plb)
{
	(void)sk;
	(void)plb;
}

static inline void bbr3_o13_plb_update_state_upon_rto(struct sock *sk,
						       struct tcp_plb_state *plb)
{
	(void)sk;
	(void)plb;
}

/* Preserve WARN condition semantics without importing __warn_printk. */
#define BBR3_WARN_ONCE(condition, format...) unlikely(!!(condition))
#define BBR3_WARN_ON_ONCE(condition) unlikely(!!(condition))

static int bbr3_resolve_runtime(void)
{
	bbr3_real___kmalloc = (void *)kallsyms_lookup_name("__kmalloc");
	if (!bbr3_real___kmalloc)
		bbr3_real___kmalloc = (void *)kallsyms_lookup_name("__kmalloc_noprof");
	bbr3_real_kfree = (void *)kallsyms_lookup_name("kfree");
	bbr3_real_get_random_u32 = (void *)kallsyms_lookup_name("get_random_u32");
	bbr3_real_get_random_u8 = (void *)kallsyms_lookup_name("get_random_u8");
	bbr3_real_register_cc =
		(void *)kallsyms_lookup_name("tcp_register_congestion_control");
	bbr3_real_unregister_cc =
		(void *)kallsyms_lookup_name("tcp_unregister_congestion_control");
	bbr3_real_alt_cb_patch_nops =
		(void *)kallsyms_lookup_name("alt_cb_patch_nops");
	bbr3_real_jiffies = (void *)kallsyms_lookup_name("jiffies");
	bbr3_linux_banner = (void *)kallsyms_lookup_name("linux_banner");

	if (!bbr3_real___kmalloc || !bbr3_real_kfree ||
	    !bbr3_real_get_random_u32 || !bbr3_real_register_cc ||
	    !bbr3_real_unregister_cc || !bbr3_real_jiffies ||
	    !bbr3_linux_banner)
		return -ENOENT;

	if (!strstr(bbr3_linux_banner, "Linux version 6.6.") ||
	    !strstr(bbr3_linux_banner, "android15-"))
		return -EPROTONOSUPPORT;

	bbr3_runtime_ready = true;
	return 0;
}
/* ---- end KernelPatch bridge ---- */
"""

FOOTER = r"""
/* ---- KPM lifecycle ----------------------------------------------------- */
#define BBR3_KPM_INFO(name, info, limit)                              \
	_Static_assert(sizeof(info) <= limit, "KPM info string too long"); \
	static const char __kpm_info_##name[] __attribute__((used))         \
	__attribute__((section(".kpm.info"), aligned(1))) = #name "=" info

BBR3_KPM_INFO(name, "kpm-bbr3-pjz110", 32);
BBR3_KPM_INFO(version, "1.0.0-alpha1", 32);
BBR3_KPM_INFO(license, "GPL v2", 32);
BBR3_KPM_INFO(author, "Axymorrsen KPM", 32);
BBR3_KPM_INFO(description,
	"Real BBRv3 KPM port for OnePlus 13 PJZ110 / Linux 6.6", 512);

typedef long (*bbr3_kpm_initcall_t)(const char *, const char *, void *);
typedef long (*bbr3_kpm_ctl0call_t)(const char *, char __user *, int);
typedef long (*bbr3_kpm_exitcall_t)(void *);

static bool bbr3_arg_has(const char *args, const char *needle)
{
	return args && needle && strstr(args, needle);
}

static long bbr3_kpm_init(const char *args, const char *event, void *reserved)
{
	int rc;

	(void)event;
	(void)reserved;

	rc = bbr3_resolve_runtime();
	if (rc)
		return rc;

	bbr_ecn_low = bbr3_arg_has(args, "ecn=1");
	rc = bbr_register();
	if (rc)
		return rc;

	bbr3_registered = true;
	return 0;
}

static long bbr3_kpm_control0(const char *args, char __user *out_msg, int outlen)
{
	char msg[192];
	int n;
	int active = atomic_read(&bbr3_active_sockets);

	if (!args || !out_msg || outlen <= 0)
		return -EINVAL;

	/* Never call tcp_unregister_congestion_control() here:
	 * KernelPatch invokes ctl0 while holding rcu_read_lock(), while the TCP
	 * unregister path calls synchronize_rcu(). Doing both would self-deadlock.
	 */
	if (!strcmp(args, "status")) {
		n = snprintf(msg, sizeof(msg),
			     "registered=%d active=%d ecn_low=%d runtime=%d unload=reboot-only",
			     bbr3_registered ? 1 : 0, active,
			     bbr_ecn_low ? 1 : 0, bbr3_runtime_ready ? 1 : 0);
		if (n < 0)
			return n;
		if (n + 1 > outlen)
			n = outlen - 1;
		return compat_copy_to_user(out_msg, msg, n + 1) < 0 ? -EFAULT : 0;
	}

	n = snprintf(msg, sizeof(msg),
		     "supported control: status; lifecycle is reboot-only on current KernelPatch");
	if (n < 0)
		return n;
	if (n + 1 > outlen)
		n = outlen - 1;
	compat_copy_to_user(out_msg, msg, n + 1);
	return -EOPNOTSUPP;
}

/* Current KernelPatch calls KPM_EXIT while holding rcu_read_lock() and frees
 * the KPM regardless of this callback's return value. A congestion-control
 * provider cannot safely unregister there because tcp_unregister_* waits for
 * an RCU grace period, and existing sockets can retain callback pointers.
 *
 * v1.0.0-alpha1 is therefore intentionally reboot-only. Do not hot-unload it.
 */
static long bbr3_kpm_exit(void *reserved)
{
	(void)reserved;
	return -EBUSY;
}

static bbr3_kpm_initcall_t __kpm_init_bbr3 __attribute__((used))
	__attribute__((section(".kpm.init"))) = bbr3_kpm_init;
static bbr3_kpm_ctl0call_t __kpm_ctl0_bbr3 __attribute__((used))
	__attribute__((section(".kpm.ctl0"))) = bbr3_kpm_control0;
static bbr3_kpm_exitcall_t __kpm_exit_bbr3 __attribute__((used))
	__attribute__((section(".kpm.exit"))) = bbr3_kpm_exit;
/* ---- end KPM lifecycle ------------------------------------------------ */
"""

def require(text: str, needle: str, label: str) -> None:
    if needle not in text:
        raise SystemExit(f"required patch anchor missing: {label}")

def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("source")
    ap.add_argument("output")
    args = ap.parse_args()

    src = Path(args.source)
    out = Path(args.output)
    text = src.read_text()

    include = '#include "bbr_compat.h"'
    require(text, include, "bbr_compat include")

    text = text.replace("tcp_jiffies32", "bbr3_tcp_jiffies32()")
    text = text.replace("kzalloc(sizeof(*bbr), GFP_ATOMIC)",
                        "bbr3_kzalloc(sizeof(*bbr), GFP_ATOMIC)")
    text = text.replace("kfree(*slot)", "bbr3_kfree(*slot)")
    text = text.replace("WARN_ONCE(", "BBR3_WARN_ONCE(")
    text = text.replace("WARN_ON_ONCE(", "BBR3_WARN_ON_ONCE(")

    replacements = {
        "tcp_plb_update_state(sk, &bbr->plb, ce_ratio);":
            "bbr3_o13_plb_update_state(sk, &bbr->plb, ce_ratio);",
        "tcp_plb_check_rehash(sk, &bbr->plb);":
            "bbr3_o13_plb_check_rehash(sk, &bbr->plb);",
        "tcp_plb_update_state_upon_rto(sk, &bbr->plb);":
            "bbr3_o13_plb_update_state_upon_rto(sk, &bbr->plb);",
        ".owner\t\t= THIS_MODULE,":
            ".owner\t\t= NULL,",
    }
    for old, new in replacements.items():
        require(text, old, old)
        text = text.replace(old, new)

    alloc_anchor = "\t\t*bbr_ca_slot(sk) = bbr;\n"
    require(text, alloc_anchor, "BBRv3 state allocation")
    text = text.replace(
        alloc_anchor,
        alloc_anchor + "\t\tatomic_inc(&bbr3_active_sockets);\n",
        1,
    )

    release_old = """static void bbr_release(struct sock *sk)
{
\tstruct bbr **slot = bbr_ca_slot(sk);

\tbbr3_kfree(*slot);
\t*slot = NULL;
}
"""
    release_new = """static void bbr_release(struct sock *sk)
{
\tstruct bbr **slot = bbr_ca_slot(sk);

\tif (*slot) {
\t\tbbr3_kfree(*slot);
\t\t*slot = NULL;
\t\tatomic_dec(&bbr3_active_sockets);
\t}
}
"""
    require(text, release_old, "BBRv3 release")
    text = text.replace(release_old, release_new, 1)

    # Insert the bridge only after token-level source rewrites. Otherwise a
    # rewrite such as tcp_jiffies32 -> bbr3_tcp_jiffies32() would rewrite the
    # bridge's own helper names a second time.
    text = text.replace(include, include + "\n" + SUPPORT, 1)

    marker = "static void __exit bbr_unregister(void)"
    require(text, marker, "Linux module exit")
    text = text[:text.index(marker)] + FOOTER + "\n"

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)

if __name__ == "__main__":
    main()
